# Generated by Django 5.2.5 on 2025-08-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_category_options_remove_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_media',
        ),
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
